# Generated by Django 2.0 on 2018-01-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('products', models.CharField(max_length=300)),
                ('listedDate', models.CharField(max_length=30)),
                ('settlementMonth', models.CharField(max_length=10)),
                ('representative', models.CharField(max_length=30)),
                ('homepage', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('prices', models.CharField(max_length=30)),
                ('fundY', models.CharField(max_length=30)),
                ('fundQ', models.CharField(max_length=30)),
            ],
        ),
    ]
