# Generated by Django 2.0 on 2018-01-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adjclose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adjclose',
            new_name='Price',
        ),
    ]
