# Generated by Django 2.0 on 2018-01-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fund_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('sales', models.FloatField(default=0.0)),
                ('biz_profit', models.FloatField(default=0.0)),
                ('net_profit', models.FloatField(default=0.0)),
                ('consol_net_profit', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
