# Generated by Django 2.0 on 2018-01-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fund_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Chart')),
            ],
        ),
        migrations.CreateModel(
            name='SfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=20)),
                ('y', models.FloatField(default=0.0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Chart')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Simulation'),
        ),
    ]
